In [1]:
import numpy as np
import random

# التمرين 1: إنشاء مصفوفات وتعديلها

إنشاء مصفوفة أحادية البعد (1D array):

أنشئ مصفوفة تحتوي على الأعداد من 1 إلى 10.
استخرج العنصر الخامس من المصفوفة.

In [45]:
arr1 = np.arange(1, 11)
arr1[4]

5

إنشاء مصفوفة ثنائية الأبعاد (2D array):

أنشئ مصفوفة 3x3 تحتوي على الأعداد من 1 إلى 9.
غير قيمة العنصر الموجود في الصف الثاني والعمود الثالث إلى 99.

In [37]:
arr2 = np.arange(1, 10)
arr2 = arr2.reshape(3, 3)
arr2[1, 2] = 99
arr2

array([[ 1,  2,  3],
       [ 4,  5, 99],
       [ 7,  8,  9]])

ضافة عنصر جديد للمصفوفة:

أضف العنصر 11 إلى المصفوفة الأولى التي أنشأتها.

In [24]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.append(arr1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# التمرين 2: العمليات الحسابية على المصفوفات

جمع وطرح المصفوفات:

أنشئ مصفوفتين 3x3 مليئتين بالقيم العشوائية.
احسب مجموع المصفوفتين.
احسب طرح المصفوفتين.

In [22]:
rand_list = [random.randint(1, 10) for i in range(9)]

a1 = np.array(rand_list)
a1 = a1.reshape(3, 3)
a1

array([[4, 9, 5],
       [6, 9, 7],
       [9, 4, 3]])

In [21]:
rand_list = [random.randint(1, 10) for i in range(9)]
a2 = np.array(rand_list)
a2 = a2.reshape(3, 3)
a2

array([[ 8,  2,  5],
       [ 9, 10, 10],
       [ 5, 10,  8]])

احسب مجموع المصفوفتين.

In [23]:
sum = a1 + a2
sum

array([[12, 11, 10],
       [15, 19, 17],
       [14, 14, 11]])

احسب طرح المصفوفتين.

In [25]:
sub = a1 - a2
sub

array([[-4,  7,  0],
       [-3, -1, -3],
       [ 4, -6, -5]])

## الضرب النقطي (Dot Product):

أنشئ مصفوفتين 2x3 و 3x2.
احسب الضرب النقطي لهاتين المصفوفتين.

In [27]:
a3 = np.array([[5, 7], [0, 9], [-5, 7]])
a3

array([[ 5,  7],
       [ 0,  9],
       [-5,  7]])

In [29]:
a4 = np.array([[8, 1, 0], [6, 2, 3]])
a4

array([[8, 1, 0],
       [6, 2, 3]])

In [32]:
a = a3.dot(a4)
a

array([[82, 19, 21],
       [54, 18, 27],
       [ 2,  9, 21]])

## حساب متوسط القيم:

In [40]:
np.average(arr2[0])

2.0

In [41]:
np.average(arr2[1])

36.0

In [42]:
np.average(arr2[2])

8.0

In [43]:
np.average(arr2)

15.333333333333334

# التمرين 3: التعامل مع الأبعاد والفهرسة

#### تغيير شكل المصفوفة:

استخدم المصفوفة 1D التي أنشأتها في التمرين 1.
حولها إلى مصفوفة 2x5.

In [46]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr1 = arr1.reshape(2, 5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### الفهرسة المتقدمة:

أنشئ مصفوفة 4x4 تحتوي على أعداد من 1 إلى 16.

In [49]:
q3 = np.arange(1, 17)
q3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [51]:
q3 = q3.reshape(4, 4)
q3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

استخرج كل العناصر الموجودة في الصفوف 1 و 3.

In [55]:
q3[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

استخرج جميع العناصر الموجودة في الأعمدة 2 و 4.

In [56]:
q3[::, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

# التمرين 4: دوال إحصائية وتحليل البيانات

#### حساب القيم الإحصائية:

أنشئ مصفوفة تحتوي على 100 عنصر عشوائي.

In [90]:
arr_rand = np.random.rand(100)
arr_rand.ndim

1

In [91]:
arr_rand.shape

(100,)

In [92]:
arr_rand *10

array([1.77456658, 0.94350709, 0.30962141, 1.55145235, 3.27555255,
       5.96036943, 7.29136065, 6.08129439, 2.10659821, 2.84536491,
       0.11143971, 1.58239635, 7.45602267, 5.25467414, 3.16885499,
       8.29209509, 4.47976798, 1.33075544, 1.91444368, 0.37115783,
       8.35833666, 0.59399168, 6.21188652, 5.78601486, 6.38664059,
       3.7804396 , 7.18234841, 4.35920188, 8.85026875, 8.96023137,
       2.07769698, 9.48252446, 3.99554001, 0.06590635, 8.00334891,
       7.43170775, 7.11451892, 1.52926942, 4.91717301, 8.12292873,
       0.24606689, 8.28279573, 2.25155203, 8.60249373, 2.97478987,
       2.19474613, 9.05623412, 1.54169767, 4.38493463, 0.82032199,
       4.74213878, 6.35854647, 9.52156041, 5.59220974, 6.22242175,
       0.86531015, 0.95515374, 2.59093184, 3.51289083, 9.81421466,
       4.14756718, 8.67627692, 2.10649004, 5.73386594, 3.81233532,
       6.2999162 , 8.96684707, 9.23343449, 2.57858487, 7.69049973,
       2.32520876, 2.05046221, 4.32414479, 3.08097886, 5.59170

احسب المتوسط، الوسيط، والانحراف المعياري لهذه المصفوفة.

##### المتوسط

In [93]:
np.average(arr_rand) # first method

0.44046460674460525

In [94]:
np.mean(arr_rand) # 2ed method

0.44046460674460525

##### الوسيط(median)

In [95]:
np.median(arr_rand)

0.43416733383872225

##### الإنحراف المعياري

In [96]:
np.std(arr_rand)

0.2885994972522447

### فرز المصفوفة:

أنشئ مصفوفة تحتوي على 10 عناصر عشوائية.

In [97]:
rand2 = np.random.rand(10)
rand2

array([0.97922324, 0.15413396, 0.94493046, 0.11156811, 0.06591557,
       0.78557527, 0.50203796, 0.88884709, 0.83906909, 0.74696288])

قم بفرز هذه المصفوفة ترتيبًا تصاعديًا.

In [100]:
rand2 = np.sort(rand2)
rand2

array([0.06591557, 0.11156811, 0.15413396, 0.50203796, 0.74696288,
       0.78557527, 0.83906909, 0.88884709, 0.94493046, 0.97922324])

احسب ترتيب المصفوفة ترتيبًا تنازليًا.

In [101]:
rand2[::-1]

array([0.97922324, 0.94493046, 0.88884709, 0.83906909, 0.78557527,
       0.74696288, 0.50203796, 0.15413396, 0.11156811, 0.06591557])

# التمرين 5: التعامل مع القيم المفقودة