In [1]:
import numpy as np

# التمرين 1: إنشاء مصفوفات وتعديلها

إنشاء مصفوفة أحادية البعد (1D array):

أنشئ مصفوفة تحتوي على الأعداد من 1 إلى 10.
استخرج العنصر الخامس من المصفوفة.

In [22]:
arr1 = np.arange(1, 11)
arr1[4]

5

إنشاء مصفوفة ثنائية الأبعاد (2D array):

أنشئ مصفوفة 3x3 تحتوي على الأعداد من 1 إلى 9.
غير قيمة العنصر الموجود في الصف الثاني والعمود الثالث إلى 99.

In [23]:
arr2 = np.arange(1, 10)
arr2 = arr2.reshape(3, 3)
arr2[1, 2] = 99
arr2

array([[ 1,  2,  3],
       [ 4,  5, 99],
       [ 7,  8,  9]])

ضافة عنصر جديد للمصفوفة:

أضف العنصر 11 إلى المصفوفة الأولى التي أنشأتها.

In [24]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.append(arr1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# التمرين 2: العمليات الحسابية على المصفوفات

جمع وطرح المصفوفات:

أنشئ مصفوفتين 3x3 مليئتين بالقيم العشوائية.
احسب مجموع المصفوفتين.
احسب طرح المصفوفتين.

In [ ]:
a1 = 