In [1]:
import numpy as np

In [2]:
a1 = np.array([10])

In [3]:
a1.ndim

1

In [4]:
a1.shape

(1,)

In [7]:
a2 = np.arange(10)

In [10]:
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
a2.ndim

1

In [12]:
a2.shape

(10,)

In [25]:
a3 = a2.reshape(2,1, 5)
a3

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [15]:
a3.ndim

2

In [16]:
a3.shape

(5, 2)

In [19]:
a4 = np.array([1, 2, 3], ndmin=3)

In [20]:
a4

array([[[1, 2, 3]]])

In [21]:
a4.ndim

3

In [22]:
a4.shape

(1, 1, 3)